[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["PredictVault"]
verbosity = 2

# Monad Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

[profile.test]
verbosity = 3
gas_reports = ["*"]
# Increase this if tests are failing due to timeout
test_timeout = 10000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
